### ISSUE TITLE
Ajax call authentication within an OWIN client

### ISSUE THREAD

**Issue by rafkuc** [thinktecture/Thinktecture.IdentityServer.v3#770]
Is there any way to mix your JS sample with standard MVC Owin authentication. We Utilize OWIN for handling authentication. Every page is secured like that but want to also implement some ajax calls within each authenticated page. When token expires, we get 302 response with no reasonable way to redirect user nor refresh the token. When trying to force the redirection within an Iframe (like on the JS sample) but using OWIN instead of the javascript library (to handle the redirection and refresh the token the "OWIN way"), we get an X-Frame-Options error since there is a form_post response mode active. If we want to use the javascript library, we cannot rewrite the secure cookie which stores the token for OWIN. Is there any way around? Or should we use a different flow?
BTW. Thank you for all the great work you are doing implementing the IdentityServer!

**Comment by brockallen** [comment]
The only other sample we have is the OAuthJS one (in the samples repo). This is using the TokenManager library we built to manage some of these complexities from the JS side. Keep in mind that it's still a work in progress.

**Comment by johnkors** [comment]
Maybe two Client setups, one with implicit and the MVC with form post?

**Comment by rafkuc** [comment]
The question then would be how to sync the access tokens? 
Or would we agree on authentication happening twice, refresh happening twice and sign out happening twice? Any suggestions are greatly appreciated!

**Comment by johnkors** [comment]
What if you at 302 responses in the js client do a window.location = myapp/login which does the regular server side login flow?

**Comment by rafkuc** [comment]
If I do the redirection in the main window during an Ajax call (e.g. to when feeding a dropdown), I lose the state of the current page (e.g. current selections, displayed messages etc). If I do that in an iframe I get the X-Frame-Options error.

**Comment by johnkors** [comment]
You have to handle state yourself anyhow. Don't see how this is any different from any other situation where you want to keep state from before login to after login?

**Comment by parkinsona** [comment]
@johnkors , how can I check for 302 responses in the js client?

**Comment by parkinsona** [comment]
I found the answer I was looking for here
http://www.codeproject.com/Articles/655086/Handling-authentication-specific-issues-for-AJAX-c

I had to create my own custom AuthAttribute that returns a 401 on an ajax request. This can then be handled in ajax OnError.

**Comment by johnkors** [comment]
well, how do you handle success today? most ajax-libs have a callback for success, error, or by status code.

**Comment by parkinsona** [comment]
To explain the issue I was having a little further.....
I'm using MVC, and when I add an ajax form it gives me 4 callbacks, onSuccess, OnError, OnComplete, OnBegin. 

When I was being redirected to get a new token, it has a 302 in fiddler, but mvc would technically return this as a 200, but because it was unauthenticated it still raises an error. When it got to the OnError handler the error code was 0. The above link, overrides the default Auth attribute, to treat this scenario as a 401. Then the OnError handler will have a 401 when it returns.

**Comment by brockallen** [comment]
MVC's ajax wrappers were always hiding too much. You really need to have finer controler over your JS ajax calls by using a library or just coding it manually. It's not that hard.

**Comment by bychkov** [comment]
@rafkuc Were you able to find a solution to this problem? We have the same problem - MVC app that gets authenticated with id_token, then it runs angular app and when token expires, we get 302 redirects...

**Comment by mschulz531** [comment]
You'll need to map the 302 returned from your controlller in response to an Ajax request to a different error code.  Our controller checks for an Ajax request, and if we find that it is an Ajax request, we return a 401 instead of a 302.  The Ajax code attempts to follow the 302 which results in undesirable behavior.  Upon receipt of the 401, we show a message asking the user to retry the operation, which causes a full page refresh, which makes everyone happy.  

We are not sure why Ajax requests seem to timeout more quickly than normal requests...this is an issue we still need to resolve.  I suspect Ajax is not handling some cookie or header correctly...

**Comment by bychkov** [comment]
That seems like a lot of hoops to jump for a pretty major use case.

**Comment by brockallen** [comment]
Well, middleware can't tell the difference in calls, unless you do something to partition up your URL space. IOW, perhaps make all your non-APIs go to ~/app and all the API calls go to ~/api.
